### ISSUE TITLE
在特定参数下容易发生错误

### ISSUE THREAD

**Issue by magicbrighter** [zhang2333/light-crawler#2]
当 timeout=2000  concurrency=50  retry=2 
任务无法持续，出现 ETIMEDOUT错误

只使用参数 interval: 1500, logger: true 正常

**Comment by zhang2333** [comment]
`ETIMEDOUT`是任务请求超时的报错，理论上不应该的。
我测试了`light-crawler/samples/news-site-zgjtb.js`，为`crawler`添加了`concurrency: 50, retry:2, requestOpts: { timeout: 2000 }`，结果正常无报错。
建议你也试一下这个，并且如果遇到了其他关于配置方面的问题，也可以拿这个demo做测试。

**Comment by zhang2333** [comment]
应该是没有问题的，如有再开
