### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by fernandosoares** [zhang2333/light-crawler#4]
Hey, how is it going?

UTF-8 websites returns a "square" in my terminal instead of á, é, ó, ô, õ, and so on and on.
Is there any support for UTF-8 characters?  Thanks

**Comment by zhang2333** [comment]
Light-Crawler supports UTF-8 by default because encoding of request is utf8.

look [encoding of request](https://github.com/request/request#requestoptions-callback)
> encoding - Encoding to be used on setEncoding of response data. If null, the body is returned as a Buffer. Anything else (including the default value of undefined) will be passed as the encoding parameter to toString() (meaning this is effectively utf8 by default). (Note: if you expect binary data, you should set encoding: null.)

Otherwise, if you want to scrape another encoding(e.g. gbk, shift jis..) page, you can try this(need some decode tools like [iconv-lite](https://github.com/ashtuchkin/iconv-lite)):

``` js
const iconv = require('iconv-lite');
crawler.addRule('http://xxx.com/xxx', function (result) {
    let html = iconv.decode(result.body, 'GBK');
    let $ = cheerio.load(html, { decodeEntities: false });
    console.log($('#sth'));
});
```

Please check whether the website you want to crawl uses uft8 charset.

**Comment by fernandosoares** [comment]
Hello again. I undertand that UTF-8 is already built-in but, please, take this by example:
`var Crawler = require('light-crawler');
var cheerio = require('cheerio');

var c = new Crawler({
    concurrency: 20,
    logger: true
});
c.addTasks(['https://olhardigital.uol.com.br/games-e-consoles/']);
c.addRule(function(result) {
    var $ = cheerio.load(result.body);
    $('.main-item .post-meta a, .item div h3 a').each(function() {
        //console.log( $(this).attr('href') );
        console.log( $(this).text() );
    });
});
c.start();`

All text() with special chars returns like a "blank square" on the teminal. Can you please run this snippet above e see the result?

Thanks in advance.

**Comment by zhang2333** [comment]
@fernandosoares 

I have tested the URL you provided, it's succeeded.

Here is the test:

Result: [Testing light-crawler for page encoding](https://runkit.io/louiszhang/testing-light-crawler-for-page-encoding/branches/master)

Source:
``` js
const Crawler = require('light-crawler');
const cheerio = require('cheerio');
const iconv = require('iconv-lite');

const c = new Crawler();

c.addTasks(['https://olhardigital.uol.com.br/games-e-consoles/']);

let rawTexts = [];
let decodedTexts = [];

c.addRule((result) => {
    let $ = cheerio.load(result.body);
    
    let decodedHtml = iconv.decode(result.body, 'iso-8859-1');
    let $$ = cheerio.load(decodedHtml, { decodeEntities: false });
    
    let selector = '.main-item .post-meta a, .item div h3 a';
    
    $(selector).each(function() {
        rawTexts.push($(this).text());
    });
    
    $$(selector).each(function() {
        decodedTexts.push($$(this).text());
    });
});

const title = 'Request(iso-8859-1): https://olhardigital.uol.com.br/games-e-consoles';
const prompt = 'Parts of scraped result:';
const raw = 'Decoded by default(utf8):';
const decoded = 'Decoded by ISO-8859-1:';

exports.endpoint = function(request, response) {
    const wrapTag = (tag, text) => `<${tag}>${text}</${tag}>`;
    const br = '<br>';
    
    c.start(() => {
        let html = wrapTag('h2', title)
            + wrapTag('h2', prompt)
            + wrapTag('h3', raw)
            + wrapTag('p', rawTexts.join(br))
            + wrapTag('h3', decoded)
            + wrapTag('p', decodedTexts.join(br));

        let wrapper = `
            <html>
                <head>
                    <title>Testing light-crawler for page encoding</title>
                </head>
                <body>
                    ${html}
                </body>
            </html>
        `;

        response.end(wrapper);
    });
}
```
