### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by ray-yuruisoft** [zhang2333/light-crawler#5]
// download the file
            let req = request(opts)
                .on('error', function (e) {
                    if (e) {
                        retry(e);
                    }
                })
                .pipe(fs.createWriteStream(file));
错误捕获要放在 pipe 前面，否则无法捕获 ESOCKETTIMEDOUT 错误。另外可以扩展下request-promise 的encoding参数，引入 iconv-lite，重写一下，至少可以支持gbk吧。

**Comment by zhang2333** [comment]
谢谢你提出的issue。
已修复该问题 49376b498a5f5b5e0c7279cae4f364c0b757be3d

也谢谢建议，不过苦于项目过于老旧难以维护以及在下的时间有限，短时间内不能给出该feature。
手动解码GBK可以参考 https://github.com/zhang2333/light-crawler/issues/4#issuecomment-293142539

**Comment by ray-yuruisoft** [comment]
不好意思，应该是这样：
request(opts)
                .on('error', function (e) {
                    if (e) {
                        retry(e);
                    }
                })
                .pipe(fs.createWriteStream(file))
                .on('finish', function (e) {
                    matchRule({ task: task, body: 'This is a download task.' });
                    res();
                })

**Comment by ray-yuruisoft** [comment]
你的编码很优雅，我非常喜欢！

**Comment by zhang2333** [comment]
@ray-yuruisoft 谢谢提醒 5ac6b70ef8243e6339a62a642b3d0aaa7427be3d
过奖过奖，两年前写的东西了远称不上优雅，其中有很多不好的实现，莫见笑才是。
另，如果要在comment里贴代码，建议使用编辑器的"Insert code"或者直接写Markdown。

**Comment by ray-yuruisoft** [comment]
你的代码，很简洁、清晰，注释很到位。只是在设计上感觉Scheduler、Downloader、PageProcesser、Pipeline，这四个功能块的耦合性很高，可扩展的接口没有暴露出来。基于该模块写的代码，在某些方面的重用率就不是很高了。希望有时间，可以重新设计一下。：）

**Comment by zhang2333** [comment]
再次感谢
